### ISSUE TITLE
Add option to ignore SSL verification

### ISSUE THREAD

**Issue by mirkan** [google/alertmanager-irc-relay#3] opened 2020-02-26 12:55 UTC
Hey,
Would it be possible to include an option to ignore SSL-certificate when using the 'irc_use_ssl: yes' ?

At the moment we get the following error:

```
Feb 26 13:50:23 prom-am-01.argos.bahnhof.net alertmanager-irc-relay[84194]: 2020/02/26 13:50:23 Starting HTTP server
Feb 26 13:50:23 prom-am-01.argos.bahnhof.net alertmanager-irc-relay[84194]: 2020/02/26 13:50:23 Connecting to IRC
Feb 26 13:50:23 prom-am-01.argos.bahnhof.net alertmanager-irc-relay[84194]: 2020/02/26 13:50:23 Backoff for 0s
Feb 26 13:50:23 prom-am-01.argos.bahnhof.net alertmanager-irc-relay[84194]: 2020/02/26 13:50:23 Could not connect to IRC: x509: certificate has expired or is not yet valid
Feb 26 13:50:23 prom-am-01.argos.bahnhof.net alertmanager-irc-relay[84194]: 2020/02/26 13:50:23 Connecting to IRC
Feb 26 13:50:23 prom-am-01.argos.bahnhof.net alertmanager-irc-relay[84194]: 2020/02/26 13:50:23 Backoff for 1s
Feb 26 13:50:24 prom-am-01.argos.bahnhof.net alertmanager-irc-relay[84194]: 2020/02/26 13:50:24 Could not connect to IRC: x509: certificate has expired or is not yet valid
Feb 26 13:50:24 prom-am-01.argos.bahnhof.net alertmanager-irc-relay[84194]: 2020/02/26 13:50:24 Connecting to IRC
Feb 26 13:50:24 prom-am-01.argos.bahnhof.net alertmanager-irc-relay[84194]: 2020/02/26 13:50:24 Backoff for 3s
```
Thank you.
@shammash

**Comment by mirkan** [comment] 2020-02-26 13:45
Found the setting:
ircConfig.SSLConfig = &tls.Config{InsecureSkipVerify: true}

So solved by rebuilding from src, but would be nice with option.

**Comment by shammash** [comment] 2020-02-27 09:43
Hi Robin,

thank you for the request.

I can add such option, but I'd like to understand a bit better your scenario.

Why it is acceptable to connect even if the cert cannot be trusted? Why not connect without SSL directly at this point?

Thank you,

Luca

**Comment by mirkan** [comment] 2020-02-27 10:11
We just havn't gotten around to change the SSL-cert yet so it's not a big issue really. It's just that normally you see clients having such an option to ignore cert-warnings. We use our irc-server somewhat publically aswell so we would like to keep SSL on only, that's why we only have SSL on.

If you can add the option it would be great, so I don't have to rebuild the src as I deploy the setup with ansible :)

Thank you!

Robin

**Comment by shammash** [comment] 2020-03-05 08:53
Hi Robin,

c122337b530ef24e12aa35f86634e4e4eecfe5ad added irc_verify_ssl .

I am going to close the issue, please feel free to reopen if it does not work as intended.

Thank you,

Luca

**Closed by shammash** 2020-03-05 08:53 UTC
