### ISSUE TITLE
Prometheus metrics support

### ISSUE THREAD

**Issue by filippog** [google/alertmanager-irc-relay#4] opened 2020-03-01 14:21 UTC
It would be nice to have support for Prometheus metrics available. A bunch of examples but I'm sure more are possible: on number of webhooks received, errors while processing hooks, number of irc messages sent, server connection status, etc

**Comment by shammash** [comment] 2020-03-05 12:00
Hi Filippo,

I believe this has been addressed in b62dde73d40923a54b32f6903292b6dec2ad7c99 .

I am going to close the issue, please feel free to reopen if it does not work as intended.

Thank you,

Luca

**Closed by shammash** 2020-03-05 12:00 UTC
