### ISSUE TITLE
Default server / irc channel?

### ISSUE THREAD

**Issue by filippog** [google/alertmanager-irc-relay#5] opened 2020-03-03 08:11 UTC
With the current default configuration the relay will attempt to connect to a real irc server and channel, I believe connecting to a non existent server e.g. `irc.example.com` would provide better defaults. e.g. in cases where multiple folks try and start the relay and all copies will connect to the same server/channel.

**Comment by shammash** [comment] 2020-03-05 09:15
Hi Filippo,

I believe this has been addressed in 96acecb3a51cb12868f0e26f38b5ced23ed41b26 .

I am going to close the issue, please feel free to reopen if it does not work as intended.

Thank you,

Luca

**Closed by shammash** 2020-03-05 09:15 UTC
